name: protein_generator
channels:
 - conda-forge
 - anaconda
dependencies:
- python=3.8
# - pip
- seaborn~=0.11.2
- matplotlib=3.2.2
- pytorch=1.13.1
- cudatoolkit=11.7
- transformers=4.17
- biopython~=1.78
- datasets=1.18.3